// agent/schemas.mjs — structured-output schemas shared by the reasoning
// engine (agent/claude-client.mjs) and the database layer (agent/db.mjs).
//
// Every Claude call that must produce actionable data uses one of these
// schemas via zodOutputFormat() + client.messages.parse(), so a malformed or
// hallucinated shape fails validation instead of silently corrupting state
// (spec section 2: "validate Claude's outputs before taking actions").

import { z } from 'zod';

// ── CandidateProfile ────────────────────────────────────────────────────────
// Built from cv.md + config/profile.yml by agent/candidate-profile.mjs — never
// generated by Claude. Included here so every module shares one shape.
export const CandidateProfileSchema = z.object({
  fullName: z.string(),
  email: z.string(),
  phone: z.string().nullable(),
  location: z.string(),
  linkedin: z.string().nullable(),
  portfolioUrl: z.string().nullable(),
  github: z.string().nullable(),
  education: z.array(
    z.object({
      degree: z.string(),
      field: z.string().nullable(),
      institution: z.string(),
      graduationDate: z.string().nullable(),
    }),
  ),
  certifications: z.array(z.string()),
  workExperience: z.array(
    z.object({
      title: z.string(),
      company: z.string(),
      location: z.string().nullable(),
      startDate: z.string().nullable(),
      endDate: z.string().nullable(),
      isCurrent: z.boolean(),
      bullets: z.array(z.string()),
    }),
  ),
  yearsOfExperience: z.number(),
  skills: z.object({
    languages: z.array(z.string()),
    frameworks: z.array(z.string()),
    databases: z.array(z.string()),
    cloud: z.array(z.string()),
    tools: z.array(z.string()),
    other: z.array(z.string()),
  }),
  projects: z.array(
    z.object({
      name: z.string(),
      technologies: z.array(z.string()),
      bullets: z.array(z.string()),
    }),
  ),
  achievements: z.array(z.string()),
  industries: z.array(z.string()),
  preferences: z.object({
    targetRoles: z.array(z.string()),
    seniority: z.array(z.string()),
    remoteAllowed: z.boolean(),
    hybridAllowed: z.boolean(),
    onsiteAllowed: z.boolean(),
    relocationOpen: z.boolean(),
    locationFlexibility: z.string().nullable(),
    compensationTargetRange: z.string().nullable(),
  }),
  workAuthorization: z.object({
    country: z.string(),
    // Free text, exactly as the candidate provided it — never inferred.
    status: z.string(),
    authorizedIn: z.array(z.string()),
    needsSponsorship: z.boolean(),
  }),
});

// ── Job ──────────────────────────────────────────────────────────────────
export const JobSchema = z.object({
  jobId: z.string(),
  source: z.string(), // provider id, e.g. "greenhouse", "lever", "ats-full-sweep"
  company: z.string(),
  title: z.string(),
  location: z.string().nullable(),
  remote: z.boolean().nullable(),
  url: z.string(),
  description: z.string().nullable(),
  postedAt: z.string().nullable(), // ISO date
  salary: z.string().nullable(),
  applicantCount: z.number().nullable(),
  discoveredAt: z.string(),
});

// ── Company ─────────────────────────────────────────────────────────────
export const CompanySchema = z.object({
  name: z.string(),
  website: z.string().nullable(),
  industry: z.string().nullable(),
  sizeEstimate: z.string().nullable(),
  headquarters: z.string().nullable(),
  description: z.string().nullable(),
  recentHiringActivity: z.string().nullable(),
  postingAgeDays: z.number().nullable(),
  salaryInfo: z.string().nullable(),
  legitimacyTier: z.enum(['verified', 'likely-legitimate', 'unverified', 'suspicious']),
  redFlags: z.array(z.string()),
  qualityScore: z.number().min(0).max(100),
});

// ── JobMatch (0-100 scoring, spec section 6) ───────────────────────────────
export const JobMatchSchema = z.object({
  score: z.number().min(0).max(100),
  breakdown: z.object({
    requiredQualifications: z.number().min(0).max(100),
    preferredQualifications: z.number().min(0).max(100),
    practicalFactors: z.number().min(0).max(100),
    resumeAlignment: z.number().min(0).max(100),
  }),
  tier: z.enum(['excellent', 'strong', 'possible', 'weak', 'reject']),
  strengths: z.array(z.string()),
  gaps: z.array(z.string()),
  reasoning: z.string(),
});

// ── ApplicationDecision ─────────────────────────────────────────────────
export const ApplicationDecisionSchema = z.object({
  decision: z.enum(['APPLY', 'SKIP', 'HUMAN_REVIEW']),
  score: z.number().min(0).max(100),
  reasons: z.array(z.string()),
  gaps: z.array(z.string()),
  eligibilityIssues: z.array(z.string()), // e.g. sponsorship mismatch, location
  notes: z.string().nullable(),
});

// ── TailoredResume ──────────────────────────────────────────────────────
export const TailoredResumeSchema = z.object({
  jobId: z.string(),
  summary: z.string(),
  // Ordered section names, reflecting emphasis/reordering — never new content.
  sectionOrder: z.array(z.string()),
  emphasizedProjects: z.array(z.string()),
  markdown: z.string(),
  keywordsIncorporated: z.array(z.string()),
  fabricationCheck: z.object({
    passed: z.boolean(),
    notes: z.string().nullable(),
  }),
});

// ── ApplicationQuestion ─────────────────────────────────────────────────
export const ApplicationQuestionSchema = z.object({
  question: z.string(),
  fieldType: z.enum(['text', 'textarea', 'select', 'radio', 'checkbox', 'number', 'file', 'unknown']),
  required: z.enum(['yes', 'no', 'unknown']),
  answer: z.string().nullable(),
  needsCandidateConfirmation: z.boolean(),
  confirmationReason: z.string().nullable(),
});

export const ApplicationAnswerSetSchema = z.object({
  jobId: z.string(),
  questions: z.array(ApplicationQuestionSchema),
});

// ── ApplicationResult ───────────────────────────────────────────────────
export const ApplicationResultSchema = z.object({
  jobId: z.string(),
  status: z.enum([
    'DISCOVERED',
    'ANALYZING',
    'QUALIFIED',
    'APPROVED',
    'APPLYING',
    'SUBMITTED',
    'HUMAN_REVIEW',
    'FAILED',
    'SKIPPED',
    'REJECTED',
    'INTERVIEW',
    'OFFER',
    'HIRED',
  ]),
  submittedAt: z.string().nullable(),
  applicationUrl: z.string().nullable(),
  resumeVersion: z.string().nullable(),
  coverLetterVersion: z.string().nullable(),
  notes: z.string().nullable(),
  failureReason: z.string().nullable(),
});

export const STATUSES = ApplicationResultSchema.shape.status.options;

// ── CvPayload ────────────────────────────────────────────────────────────
// Matches the JSON Input Schema documented in modes/pdf.md exactly, so a
// payload built by the autonomous agent renders through the SAME
// build-cv-html.mjs / generate-pdf.mjs pipeline the interactive `pdf` mode
// uses — one ATS-optimized template, one code path, never reimplemented.
export const CvPayloadSchema = z.object({
  lang: z.string().default('en'),
  page_format: z.enum(['letter', 'a4']).default('letter'),
  candidate: z.object({
    name: z.string(),
    phone: z.string().optional(),
    email: z.string(),
    linkedin: z.object({ url: z.string(), display: z.string() }).optional(),
    github: z.object({ url: z.string(), display: z.string() }).optional(),
    portfolio: z.object({ url: z.string(), display: z.string() }).optional(),
    location: z.string(),
    photo: z.string().optional(),
    photo_style: z.enum(['rounded', 'circle', 'square']).optional(),
  }),
  summary: z.string(),
  competencies: z.array(z.string()),
  experience: z.array(
    z.object({
      company: z.string(),
      role: z.string(),
      location: z.string().optional(),
      dates: z.string(),
      bullets: z.array(z.string()),
    }),
  ),
  projects: z.array(
    z.object({
      name: z.string(),
      badge: z.string().optional(),
      tech: z.string().optional(),
      description: z.string(),
    }),
  ),
  education: z.array(
    z.object({
      title: z.string(),
      org: z.string(),
      year: z.string(),
      description: z.string().optional(),
    }),
  ),
  certifications: z.array(z.object({ title: z.string(), org: z.string(), year: z.string() })),
  awards: z.array(
    z.object({ title: z.string(), org: z.string().optional(), year: z.string().optional() }),
  ),
  skills: z.array(z.object({ category: z.string(), items: z.string() })),
});
